branches::
  only:
    master
language: generic
sudo: required
services:
  - docker
script:
  - docker build -t registry.heroku.com/mux-resume/web .
after_success:
  - docker login -u=_ -p="$HEROKU_AUTH_TOKEN" registry.heroku.com
  - docker push registry.heroku.com/mux-resume/web
  - imageId=$(docker inspect registry.heroku.com/mux-resume/web --format={{.Id}})
  - |
    curl -n -X PATCH https://api.heroku.com/apps/mux-resume/formation \
    -d '{"updates":[{"type":"web","docker_image":"'"$imageId"'"}]}' \
    -H "Content-Type: application/json" \
    -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
    -H "Authorization: Bearer $HEROKU_AUTH_TOKEN"
